fix mooo new script to remove colons in path (colons not supported on windows)

diff --git a/mooo b/mooo
--- a/mooo
+++ b/mooo
@@ -1,7 +1,21 @@
 #!/bin/bash
 
-cowPath="/usr/share/cowsay"
-cowfiles=$(find $cowPath -name '*.cow');
+fortunePath=`which fortune`
+
+if [ ! -x $fortunePath ]; then
+  echo 'Could not find "fortune" program'
+  exit 1;
+fi;
+
+cowPath=`which cowthink`
+
+if [ ! -x $cowPath ]; then
+  echo 'Could not find "cowsay" program'
+  exit 1;
+fi;
+
+cowDir="$(dirname $cowPath)/../share/cows"
+cowfiles=$(find $cowDir -name '*.cow');
 
 cowfilesList=(`echo $cowfiles`);
 
@@ -16,6 +30,7 @@ mstart=' _______'
 mend=' -------'
 if [ -x `which fortune` -a -x `which cowsay` ]; then
   echo "Using cow file: $cowfile"
-  fortune -ac | cowthink -n -f $cowfile | sed "/$mstart/,/$mend/ s/^(\\|)$//g"
+  # $fortunePath -ac | $cowPath -n -f $cowfile | sed "/$mstart/,/$mend/ s/^(\\|)$//g"
+  $fortunePath -a | $cowPath -n -f $cowfile | sed "/$mstart/,/$mend/ s/^(\\|)$//g"
 fi;
 
